Repository AY2223S1-CS2103T-F12-2/tp, pull requests merged in 2022-11, with the labels that each got.

#171 Bugfix addTask feature
  src/main/java/seedu/address/model/task/Task.java
Labels: type.Bug, severity.Low

#181 Hide email for unassigned task
  src/main/java/seedu/address/ui/TaskCard.java
Labels: severity.Low

#185 Update task on person edit
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: priority.High, severity.High
